(refactor) project settings update
matrix-org/matrix-ios-sdk pull request #1543
Opened 2022-08-05 23:49 UTC by mredig

updated to match Xcode recommended settings. There were some target version bumps, so if you want me to revert those, that's fine.

Signed-off-by: Michael Redig <hybrids-07-baggage at icloud.com>
### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [x] Pull request contains a changelog file in ./changelog.d. See https://github.com/matrix-org/matrix-ios-sdk/blob/develop/CONTRIBUTING.md#changelog
* [ ] Pull request includes a [sign off](https://github.com/matrix-org/matrix-ios-sdk/blob/develop/CONTRIBUTING.md#sign-off)

2022-08-09 11:24 UTC, pixlwave requested changes
Hi @mredig, thanks for this PR. Looks fine to me, but yes please could you revert the deployment target back to iOS 11 for us 🙏.

2022-08-10 03:04 UTC, mredig commented
targets reverted :)

2022-08-12 11:26 UTC, pixlwave approved these changes

2022-08-12 11:27 UTC, merged

2022-08-12 11:27 UTC, pixlwave commented
Thanks @mredig