Add Hold Support for CallKit
matrix-org/matrix-ios-sdk pull request #964
Opened 2020-12-02 19:48 UTC by ismailgulek

2020-12-03 10:57 UTC, ismailgulek commented
This is how it looks like:

![IMG_0018](https://user-images.githubusercontent.com/3072286/101000804-6958c780-356f-11eb-856f-aa3eee527ab9.PNG)

2020-12-04 04:50 UTC, Rebeccataylor17 approved these changes

2020-12-04 04:51 UTC, Rebeccataylor17 requested changes
``

2020-12-07 09:54 UTC, manuroe approved these changes

2020-12-07 11:32 UTC, merged