Added encryption for MXRealmCryptoStore
matrix-org/matrix-ios-sdk pull request #973
Opened 2020-12-14 14:32 UTC by gileluard

2020-12-15 10:53 UTC, ismailgulek requested changes

2020-12-15 10:53 UTC, ismailgulek commented on MatrixSDK/Crypto/Data/Store/MXRealmCryptoStore/MXRealmCryptoStore.m
> +    NSLog(@"[MXRealmCryptoStore] realmForUser: end after %fs", [[NSDate date] timeIntervalSinceDate:startDate]);
```suggestion
    NSLog(@"[MXRealmCryptoStore] realmForUser: end after %.3fms", [[NSDate date] timeIntervalSinceDate:startDate] * 1000);
```

Let's be consistent across timing values.

2020-12-15 11:41 UTC, SBiOSoftWhare commented on MatrixSDK/Crypto/Data/Store/MXRealmCryptoStore/MXRealmCryptoStore.m
> +        NSURL *sharedFileURL = [self sharedFileURLWithApplicationGroupIdentifier:applicationGroupIdentifier FileName:realmFile];
```suggestion
        NSURL *sharedFileURL = [self sharedFileURLWithApplicationGroupIdentifier:applicationGroupIdentifier fileName:realmFile];
```

2020-12-15 11:41 UTC, SBiOSoftWhare commented on MatrixSDK/Crypto/Data/Store/MXRealmCryptoStore/MXRealmCryptoStore.m
> +NSString *const kMXRealmCryptoStoreDataType = @"org.matrix.sdk.MXRealmCryptoStoreDataType";
For external constants it is recommended to not use the `k` prefix: `MXRealmCryptoStoreDataType`

2020-12-15 16:28 UTC, SBiOSoftWhare approved these changes

2020-12-15 20:26 UTC, ismailgulek commented on MatrixSDK/Crypto/Data/Store/MXRealmCryptoStore/MXRealmCryptoStore.m
> ++ (BOOL)shouldMoveToEncryptedDBWithEncryptedFilename:(NSString *)fileName applicationGroupIdentifier:(NSString *)applicationGroupIdentifier defaultRealmPathURL:(NSURL *)defaultRealmPathURL
Thanks for the `_Nullable`. Looks like we still lack the check inside the method. `-[NSFileManager containerURLForSecurityApplicationGroupIdentifier:applicationGroupIdentifier]` will cause a crash for `applicationGroupIdentifier`.

2020-12-15 20:28 UTC, ismailgulek commented on MatrixSDK/Crypto/Data/Store/MXRealmCryptoStore/MXRealmCryptoStore.m
> +        [self moveToShareContainerFrom:defaultRealmFileURL to:sharedFileURL error:&error];
This seems better, thanks.

2020-12-16 11:39 UTC, ismailgulek approved these changes

2021-01-11 08:53 UTC, manuroe requested changes
We need to check if Realm can support multi process when encrypted.

2021-02-23 10:54 UTC, manuroe commented
Closed in favour of https://github.com/matrix-org/matrix-ios-sdk/pull/1027

2021-02-23 10:54 UTC, closed without merging